<?php
/**
 * @file
 * Code for the People feature.
 */

include_once 'luggage_people.features.inc';

/**
 * Add a My Public Profile link to toolbar.
 *
 * Assumes a content type with machine name 'people'.
 */

function luggage_people_menu() {
  $items['admin/myprofile'] = array(
    'title' => 'My Public Profile',
    'description' => 'Edit your public profile',
    'page callback' => 'luggage_people_profile_link',
    'access arguments' => array('edit own people content'),
    'weight' => '15',
  );
  return $items;
}

function luggage_people_profile_link() {
  global $user;

  // Discover the nid of this user's profile.
  $data = db_query("SELECT COUNT(nid) as ct, nid FROM {node} n WHERE n.type='people' AND n.uid=:uid", array(':uid' => $user->uid))->fetchObject();
  switch ($data->ct) {
    case 0:
      // User does not yet have a profile.
      drupal_goto('node/add/people');
      break;
    case 1:
      // Normal case: found user's profile. Go there.
      drupal_goto("node/$data->nid");
      break;
    // User has authored more than one. Send to Content.
    default:
      drupal_goto('admin/content');
  }
}

/**
 * Implements hook_update_projects_alter().
 */
function luggage_people_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['luggage_people']);
}

// Adds CSS to Views
/**
 * Implements hook_views_pre_render().
 */
function luggage_people_views_pre_render(&$view) {
  $people_view = array('people', 'people');
  if (in_array($view->name, $people_view)) {
    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
//    $people_module_path = drupal_get_path('module', 'people');
    //drupal_add_js($contextual_module_path . '/contextual.js');
    drupal_add_css(drupal_get_path('module', 'luggage_people') . '/css/luggage_people.css');
  }
}


// Adds CSS to view display of people node type but not the edit display
function luggage_people_preprocess_page(&$vars) {
  // Global node.
  $node = menu_get_object();
  if (!empty($node) && $node->type == 'people' || arg(0).arg(1).arg(2) == 'nodeaddpeople') {
    drupal_add_css(drupal_get_path('module', 'luggage_people') . '/css/luggage_people.css');
  }
}

// Adding support to discover template files
/**
 * Implements hook_theme_registry_alter()
 **/
function people_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'luggage_people');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _luggage_people_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
 */
function _luggage_people_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}