<?php
/**
 * @file
 * Code for the People feature.
 */

include_once 'people.features.inc';

/**
 * Implements hook_update_projects_alter().
 */
function people_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['people']);
}

// Adds CSS to Views
/**
 * Implements hook_views_pre_render().
 */
function people_views_pre_render(&$view) {
  $people_view = array('people', 'people');
  if (in_array($view->name, $people_view)) {
    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
//    $people_module_path = drupal_get_path('module', 'people');
    //drupal_add_js($contextual_module_path . '/contextual.js');
    drupal_add_css(drupal_get_path('module', 'people') . '/css/people.css');
  }
}


// Adds CSS to view display of people node type but not the edit display
function people_preprocess_page(&$vars) {
  // Global node.
  $node = menu_get_object();
  if (!empty($node) && $node->type == 'people' && arg(2) === null) {
    drupal_add_css(drupal_get_path('module', 'people') . '/css/people.css');
  }
}

// Adding support to discover template files
/**
 * Implements hook_theme_registry_alter()
 **/
function people_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'people');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _people_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
 */
function _people_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}