<?php
/**
 * @file
 * Code for the People feature.
 */

include_once 'people.features.inc';

/**
 * Implements hook_views_pre_render().
 */
function people_views_pre_render(&$view) {
  $people_view = array('people', 'people');
  if (in_array($view->name, $people_view)) {
    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
    $people_module_path = drupal_get_path('module', 'people');
    //drupal_add_js($contextual_module_path . '/contextual.js');
    drupal_add_css($people_module_path . '/css/people.css');
  }
}

/**
 * Implements hook_update_projects_alter().
 */
function people_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['people']);
}