<?php
/**
 * @file
 * Code for the People feature.
 */

include_once 'people.features.inc';

//function people_node_access($node, $op, $account) {
//  if ($op == 'create' && $node->type == 'the_content_type') {
//    // Grab the number of nodes of this type the user has already created.
//    $args = array(':type' => 'people', ':uid' => $account->uid);
//    $node_count = db_query('SELECT COUNT(nid) FROM {node} WHERE type = :type AND uid = :uid')->fetchField();
//
//    // Get the max allowed number of nodes
//    $limit = '1';
//
//    // If the user us at/has exceeded the limit, set a message and send the user
//    // off somewhere else.
//    if ($limit >= $node_count) {
//      return NODE_ACCESS_DENY;
//    }
//
//    return NODE_ACCESS_ALLOW;
//  }
//
//  return NODE_ACCESS_IGNORE;
//}

/**
 * Implements hook_views_pre_render().
 */
function people_views_pre_render(&$view) {
  $people_view = array('people', 'people');
  if (in_array($view->name, $people_view)) {
    //drupal_add_js(drupal_get_path('module', 'td_deals') . '/td_deals.js');
    $people_module_path = drupal_get_path('module', 'people');
    //drupal_add_js($contextual_module_path . '/contextual.js');
    drupal_add_css($people_module_path . '/css/people.css');
  }
}