<?php
/**
 * @file
 * Code for the luggage_people_expertise feature.
 */

include_once 'luggage_people_expertise.features.inc';

/**
 *  Implements hook_views_pre_view()
 */
function luggage_people_expertise_views_pre_view(&$view, &$display_id, &$args) {
  if($view->name == 'expertise') {
    drupal_add_css(drupal_get_path('module', 'luggage_people_expertise').'/css/luggage_people_expertise.css');
  }
}
