<?php

/**
 * @file
 * Add a My Public Profile link to toolbar.
 * 
 * Assumes a content type with machine name 'people'.
 */

function myprofiletoolbarlink_menu() {
  $items['admin/myprofile'] = array(
    'title' => 'My Public Profile',
    'description' => 'Edit your public profile',
    'page callback' => 'myprofiletoolbarlink_profile_link',
    'access arguments' => array('edit own people content'),
    'weight' => '15',
  );
  return $items;
}

function myprofiletoolbarlink_profile_link() {
  global $user;
    
  // Discover the nid of this user's profile.
  $data = db_query("SELECT COUNT(nid) as ct, nid FROM {node} n WHERE n.type='people' AND n.uid=:uid", array(':uid' => $user->uid))->fetchObject();
  switch ($data->ct) {
    case 0:
      // User does not yet have a profile.
      drupal_goto('node/add/people');
      break;
    case 1:
      // Normal case: found user's profile. Go there.
      drupal_goto("node/$data->nid");
      break;
      // User has authored more than one. Send to Content.
    default:
      drupal_goto('admin/content');  
  }
}